from datetime import datetime
from pathlib import Path
from typing import Optional

from app.core.config import settings
from app.crud.report import create_report
from app.schemas.schemas import ReportRead, ReportRequest


def generate_report(db, report_request: ReportRequest) -> ReportRead:
    report_dir = settings.FILE_UPLOAD_DIR
    report_dir.mkdir(parents=True, exist_ok=True)

    file_name = f"report_{report_request.report_type}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.txt"
    file_path = report_dir / file_name
    report_contents = [
        f"Title: {report_request.title}",
        f"Report Type: {report_request.report_type}",
        f"Generated: {datetime.utcnow().isoformat()}",
        f"Start Date: {report_request.start_date}",
        f"End Date: {report_request.end_date}",
        "\n---\n",
        "This report contains summary data generated by the AI Business Copilot backend.",
    ]

    file_path.write_text("\n".join(str(line) for line in report_contents), encoding="utf-8")

    report_record = create_report(
        db,
        {
            "title": report_request.title,
            "report_type": report_request.report_type,
            "generated_date": datetime.utcnow(),
            "file_path": str(file_path),
        },
    )
    return ReportRead.from_orm(report_record)
